### PR TITLE
Fix for webpack

### PR DESCRIPTION
**Pull request by awlayton**
Fixes "Cannot read property 'setTimeout' of undefined"

### CODE REVIEW

**Comment by andreiavrammsd** [comment]
@awlayton, can you please share a full code setup where this issue can be reproduced?

**Comment by awlayton** [comment]
To reproduce, simply start a new project with `create-react-app` then add the following lines to `App.js`:
```javascript
import {Apixu} from 'apixu';                                                       
                                                                                   
const apixu = new Apixu({apikey: /* API KEY */});               
apixu.current(/* location string */) ;
```

And you will get the error `Unhandled Rejection (TypeError): Cannot read property 'setTimeout' of undefined`

**Comment by andreiavrammsd** [comment]
@awlayton, the issue is actually because of the `setTimeout` function not being defined when running the library in the browser. The implementation was done only for with back end.

Please take a look at [this fix](https://github.com/andreiavrammsd/apixu-nodejs/commit/b990369cf9ab254484deb47d8f2e241f2b5f5fcc) and let me know what you think.
You can test it by adding to your `package.json`:
```
"apixu": "andreiavrammsd/apixu-nodejs#timeout-fix"
```
If you plan to use the library in a public project, make sure you won't expose your API key.

**Comment by awlayton** [comment]
Your fix seems good to me and works in my application.

**Comment by andreiavrammsd** [comment]
I've just released the fix. Thank you!

**Pull request closed without merging**
